spring:
  main:
    banner-mode: off
  datasource:
    url: jdbc:mysql://${MYSQL_SERVER:localhost}:${MYSQL_PORT:3306}/${DB_NAME:kharazim_id_generator_db}?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:123456}
    hikari:
      maximum-pool-size: 200
      minimum-idle: 10

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

logging:
  level:
    root: info

dubbo:
  application:
    name: ${spring.application.name:kharazim-id-generator}
    check-serializable: false
    serialize-check-status: WARN
    qos-enable: false
  registry:
    address: nacos://${NACOS_SERVER_HOST:localhost}:${NACOS_SERVER_PORT:8848}?namespace=kharazim
    group: kharazim-dubbo
    username: ${NACOS_USERNAME:}
    password: ${NACOS_PASSWORD:}
  protocol:
    name: dubbo
    port: -1
  consumer:
    check: false