server:
  port: 9408
  servlet:
    context-path: /kharazim-api

spring:
  main:
    banner-mode: off
  application:
    name: kharazim
  datasource:
    url: jdbc:mysql://${MYSQL_SERVER:localhost}:${MYSQL_PORT:3306}/${DB_NAME:kharazim_db}?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:123456}
    hikari:
      maximum-pool-size: 200
      minimum-idle: 10
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      database: ${REDIS_DATABASE:0}

  servlet:
    multipart:
      max-file-size: 10MB
  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss
  cache:
    type: redis
    redis:
      key-prefix: KHARAZIM_CACHE
      time-to-live: 20m
      caches:
        - name: CURRENT_USER_INFO
          capacity: 10
          ttl: 5m
        - name: ADDRESS_TREE_NODE
          capacity: 20
          ttl: 24h

    caffeine:
      default-ttl: 20m
      caches:
        - name: CURRENT_USER_INFO
          capacity: 10
          ttl: 5m
        - name: ADDRESS_TREE_NODE
          capacity: 20
          ttl: 24h

mybatis-plus:
  global-config:
    banner: false

logging:
  level:
    root: info
    com.zaxxer.hikari.pool.HikariPool: error
  charset:
    console: UTF-8

knife4j:
  enable: true
  production: false

system:
  global:
    code-generator: datasource
    enable-print-request-log: true
    request-log:
      ignore-urls:
        - ${server.servlet.context-path}/
        - ${server.servlet.context-path}/bootstrap
        - /**/favicon.ico
        - /**/api-docs/**
        - /**/api-docs.yaml/**
        - /**/webjars/**
        - /**/swagger-resources/**
        - /**/actuator/**
        - /**/system/request-log/**
        - /**/system/address/**
    auth:
      allow-multi-login: true
      enable: true
      white-list:
        - /**/login
        - /**/logout
        - /**/system/file/fetch/*

springdoc:
  group-configs:
    - group: "系统基础服务"
      packages-to-scan:
        - com.tyrael.kharazim.web.controller.system
    - group: "系统用户管理"
      packages-to-scan:
        - com.tyrael.kharazim.web.controller.user
    - group: "诊所管理"
      packages-to-scan:
        - com.tyrael.kharazim.web.controller.clinic
    - group: "会员档案"
      packages-to-scan:
        - com.tyrael.kharazim.web.controller.customer
    - group: "处方管理"
      packages-to-scan:
        - com.tyrael.kharazim.web.controller.prescription
    - group: "商品中心"
      packages-to-scan:
        - com.tyrael.kharazim.web.controller.product
    - group: "储值管理"
      packages-to-scan:
        - com.tyrael.kharazim.web.controller.recharge
    - group: "结算管理"
      packages-to-scan:
        - com.tyrael.kharazim.web.controller.settlement
    - group: "供应商管理"
      packages-to-scan:
        - com.tyrael.kharazim.web.controller.supplier
    - group: "采购管理"
      packages-to-scan:
        - com.tyrael.kharazim.web.controller.purchase
    - group: "药房管理"
      packages-to-scan:
        - com.tyrael.kharazim.web.controller.pharmacy
    - group: "示例功能"
      packages-to-scan:
        - com.tyrael.kharazim.web.controller.demo

file:
  home-path: ${FILE_HOME:}
  root-dir: ${FILE_ROOT_DIR:.kharazim_files}
  max-age: ${FILE_CACHE_AGE:5m}