server:
  port: 9408
  servlet:
    context-path: /kharazim-api

spring:
  main:
    banner-mode: off
  application:
    name: kharazim
  datasource:
    url: jdbc:mysql://${MYSQL_SERVER:localhost}:${MYSQL_PORT:3306}/kharazim_db?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&useAffectedRows=true
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:123456}
  servlet:
    multipart:
      max-file-size: 10MB

mybatis-plus:
  global-config:
    banner: false

logging:
  level:
    root: info
  charset:
    console: UTF-8

knife4j:
  enable: true
  production: false

system:
  global:
    code-generator: datasource
    enable-print-request-log: true
    request-log:
      ignore-urls:
        - ${server.servlet.context-path}/
        - ${server.servlet.context-path}/bootstrap
        - /**/favicon.ico
        - /**/api-docs/**
        - /**/webjars/**
        - /**/swagger-resources/**
        - /**/system/request-log/**
        - /**/system/address/**
        - /**/system/dict/**/pages
        - /**/system/dict/**/form
        - /**/system/dict/types/*/items
    auth:
      allow-multi-login: true
      enable: true
      white-list:
        - /**/login
        - /**/logout

springdoc:
  group-configs:
    - group: "系统基础服务"
      packages-to-scan:
        - com.tyrael.kharazim.web.controller.system
    - group: "系统用户管理"
      packages-to-scan:
        - com.tyrael.kharazim.web.controller.user
    - group: "诊所管理"
      packages-to-scan:
        - com.tyrael.kharazim.web.controller.clinic
    - group: "会员档案"
      packages-to-scan:
        - com.tyrael.kharazim.web.controller.customer
    - group: "处方管理"
      packages-to-scan:
        - com.tyrael.kharazim.web.controller.prescription
    - group: "商品中心"
      packages-to-scan:
        - com.tyrael.kharazim.web.controller.product
    - group: "储值管理"
      packages-to-scan:
        - com.tyrael.kharazim.web.controller.recharge
    - group: "结算管理"
      packages-to-scan:
        - com.tyrael.kharazim.web.controller.settlement
    - group: "供应商管理"
      packages-to-scan:
        - com.tyrael.kharazim.web.controller.supplier