server:
  port: 9408
  servlet:
    context-path: /kharazim-api

spring:
  main:
    banner-mode: off
  application:
    name: kharazim
  datasource:
    url: jdbc:mysql://${MYSQL_SERVER:localhost}:${MYSQL_PORT:3306}/kharazim?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&useAffectedRows=true
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:123456}

logging:
  level:
    root: info
  charset:
    console: UTF-8

knife4j:
  enable: true
  production: false

system:
  global:
    use-inner-mock-redis: true
    code-generator: datasource
    enable-print-request-log: true
    request-log:
      ignore-urls:
        - ${server.servlet.context-path}/
        - /**/favicon.ico
        - /**/api-docs/**
        - /**/webjars/**
        - /**/swagger-resources/**
        - /**/system/request-log/**
        - /**/system/address/**
        - /**/system/dict/**/pages
        - /**/system/dict/**/form
        - /**/system/dict/types/*/items

springdoc:
  group-configs:
    - group: "系统接口"
      packages-to-scan:
        - com.tyrael.kharazim.web.controller.system
    - group: "用户管理"
      packages-to-scan:
        - com.tyrael.kharazim.web.controller.user