server:
  port: 9408
  servlet:
    context-path: /kharazim-api

spring:
  main:
    banner-mode: off
  application:
    name: kharazim
  datasource:
    url: jdbc:mysql://${MYSQL_SERVER:localhost}:${MYSQL_PORT:3306}/kharazim?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&useAffectedRows=true
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:123456}

logging:
  level:
    root: info
  charset:
    console: UTF-8

knife4j:
  enable: true
  production: false

system:
  global:
    use-inner-mock-redis: true
    code-generator: datasource
