auth:
  login:
    whitelist:
      - "/*/auth/login"
      - "/*/auth/logout"
      - "/*/v2/api-docs"

spring:
  cloud:
    gateway:
      context-path: /kharazim-api
      routes:
        - id: user_api_route
          uri: lb://kharazim-user-api
          predicates:
            - Path=/kharazim-user-api/**, /user/**, /auth/**, /roles/**
          filters:
            - RewritePath=/kharazim-user-api/?(?<segment>.*), /$\{segment}

        - id: basic_data_api_route
          uri: lb://kharazim-basic-data
          predicates:
            - Path=/system/**, /clinic/**

dubbo:
  application:
    name: kharazim-dubbo-gateway
    check-serializable: false
    serialize-check-status: WARN
    qos-enable: false
  registry:
    address: nacos://${NACOS_SERVER_HOST:localhost}:${NACOS_SERVER_PORT:8848}?namespace=kharazim
    group: kharazim-dubbo
    username: ${NACOS_USERNAME:}
    password: ${NACOS_PASSWORD:}
  protocol:
    name: dubbo
    port: -1
  consumer:
    check: false

knife4j:
  gateway:
    enabled: true
    routes:
      - name: 用户服务
        url: /kharazim-user-api/v3/api-docs?group=default
        service-name: user-api-service
    basic:
      enable: true