auth:
  login:
    whitelist:
      - "/*/auth/login"
      - "/*/auth/logout"
      - "/*/v2/api-docs"
      - "/*/system/file/fetch/*"

spring:
  cloud:
    gateway:
      context-path: /kharazim-api
      routes:
        - id: user_api_route
          uri: lb://kharazim-user-api
          predicates:
            - Path=
              /user/**,
              /auth/**,
              /roles/**,
              /user-api/**
          filters:
            - RewritePath=/user-api/?(?<segment>.*), /$\{segment}

        - id: basic_data_api_route
          uri: lb://kharazim-basic-data
          predicates:
            - Path=
              /system/**,
              /clinic/**,
              /customer/**,
              /basic-api/**
          filters:
            - RewritePath=/basic-api/?(?<segment>.*), /$\{segment}

        - id: product_api_route
          uri: lb://kharazim-product
          predicates:
            - Path=
              /product/**,
              /product-api/**
          filters:
            - RewritePath=/product-api/?(?<segment>.*), /$\{segment}

        - id: purchase_api_route
          uri: lb://kharazim-purchase
          predicates:
            - Path=
              /supplier/**,
              /purchase-order/**,
              /purchase-api/**
          filters:
            - RewritePath=/purchase-api/?(?<segment>.*), /$\{segment}

        - id: pharmacy_api_route
          uri: lb://kharazim-pharmacy
          predicates:
            - Path=
              /inventory/**,
              /inbound-order/**,
              /outbound-order/**,
              /pharmacy-api/**
          filters:
            - RewritePath=/pharmacy-api/?(?<segment>.*), /$\{segment}

        - id: diagnosis_treatment_api_route
          uri: lb://kharazim-diagnosis-treatment
          predicates:
            - Path=
              /prescription/**,
              /diagnosis-treatment-api/**
          filters:
            - RewritePath=/diagnosis-treatment-api/?(?<segment>.*), /$\{segment}

        - id: finance_api_route
          uri: lb://kharazim-finance
          predicates:
            - Path=
              /recharge-card-type/**,
              /recharge-card/**,
              /finance-api/**
          filters:
            - RewritePath=/finance-api/?(?<segment>.*), /$\{segment}

knife4j:
  gateway:
    routes:
      - name: 用户服务
        url: /user-api/v3/api-docs
      - name: 基础服务
        url: /basic-api/v3/api-docs
      - name: 商品服务
        url: /product-api/v3/api-docs
      - name: 采购服务
        url: /purchase-api/v3/api-docs
      - name: 药房服务
        url: /pharmacy-api/v3/api-docs
      - name: 诊疗服务
        url: /diagnosis-treatment-api/v3/api-docs
      - name: 财务服务
        url: /finance-api/v3/api-docs

    basic:
      enable: true

system:
  request-log:
    ignore-urls:
      - "/*/favicon.ico"
      - "/*/auth/logout"
      - "/*/api-docs/*"
      - "/*/api-docs.yaml/*"
      - "/*/webjars/*"
      - "/*/swagger-resources/*"
      - "/*/actuator/*"
      - "/*/system/request-log/*"
      - "/*/system/address/*"
      - "/*/system/file/*"