auth:
  login:
    whitelist:
      - "/*/auth/login"
      - "/*/auth/logout"
      - "/*/v2/api-docs"
      - "/*/system/file/fetch/*"

spring:
  cloud:
    gateway:
      context-path: /kharazim-api
      routes:
        - id: user_api_route
          uri: lb://kharazim-user-api
          predicates:
            - Path=/user-api/**, /user/**, /auth/**, /roles/**
          filters:
            - RewritePath=/user-api/?(?<segment>.*), /$\{segment}

        - id: basic_data_api_route
          uri: lb://kharazim-basic-data
          predicates:
            - Path=/basic-api/**, /system/**, /clinic/**, /customer/**, /recharge-card-type/**, /recharge-card/**
          filters:
            - RewritePath=/basic-api/?(?<segment>.*), /$\{segment}

knife4j:
  gateway:
    routes:
      - name: 用户服务
        url: /user-api/v3/api-docs?group=default
        service-name: user-api-service
      - name: 基础服务
        url: /basic-api/v3/api-docs?group=default
        service-name: basic-api-service
    basic:
      enable: true

system:
  request-log:
    ignore-urls:
      - "/*/favicon.ico"
      - "/*/auth/logout"
      - "/*/api-docs/*"
      - "/*/api-docs.yaml/*"
      - "/*/webjars/*"
      - "/*/swagger-resources/*"
      - "/*/actuator/*"
      - "/*/system/request-log/*"
      - "/*/system/address/*"
      - "/*/system/file/*"